### ISSUE TITLE
cant compile the demo example have all 1.0.21 library installed open example this error bellow latest arduino IDE 

### ISSUE THREAD

**Issue by mcousine** [Azure/azure-iot-arduino#48]
AzureIoTHub, AzureIoTUtility, AzureIoTProtocol_MQTT no sample would compile with error bellow  all 1.0.21

In file included from /Users/michelcousineau/Documents/Arduino/libraries/AzureIoTUtility/src/azure_c_shared_utility/xlogging.h:57:0,
                 from /Users/michelcousineau/Documents/Arduino/libraries/AzureIoTHub/src/sdk/serializer.h:58,
                 from /Users/michelcousineau/Documents/Arduino/libraries/AzureIoTHub/src/AzureIoTHub.h:9,
                 from /Users/michelcousineau/Documents/Arduino/libraries/AzureIoTProtocol_MQTT/examples/simplesample_mqtt/simplesample_mqtt.ino:42:
/Users/michelcousineau/Documents/Arduino/libraries/AzureIoTHub/src/esp8266/azcpgmspace.h:15:53: fatal error: azure_c_shared_utility\crt_abstractions.h: No such file or directory
 #include "azure_c_shared_utility\crt_abstractions.h"
                                                     ^
compilation terminated

**Comment by tameraw** [comment]
@mcousine - Please make sure that you have the ArduinoIoTUtility included.
Also, if you can provide more details on what is your environment, that would help.

**Comment by mamokarz** [comment]
Version 1.0.30 fix the back slash on this include.
